name: ESLint

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run ESLint
        run: npx eslint ./src/ ./examples/ ./scripts/ index.js --max-warnings 0
