name: Release
on:
  pull_request_target:
    types: [opened]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Job for transpiler the code
      - name: 'Transpiler-JS Action'
        uses: jossydevers/transpiler-js@v1.0.0
        with:
          typename: 'release' # (OPTIONAL)
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1


      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release
          branch: prod
      - uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "Pull request has been merged to prod."
